title: Unnati Sonawala
email: unnati@vt.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Unnati. I am a PhD candidate at Virginia Tech.
  This website is under construction. Please check back in a few days.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: u__progress
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
